// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADkAjs5WA8UFqB1vMTigUi7_1gFycdcPA',
    appId: '1:724762452264:web:6d41dabe4d63b48105b01d',
    messagingSenderId: '724762452264',
    projectId: 'testtrello-57ec7',
    authDomain: 'testtrello-57ec7.firebaseapp.com',
    storageBucket: 'testtrello-57ec7.firebasestorage.app',
    measurementId: 'G-BTKYEHLHCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQmTDvmK7BOD8ztIueYGstcDahWnMWMg',
    appId: '1:724762452264:android:2f2fad6d594d791f05b01d',
    messagingSenderId: '724762452264',
    projectId: 'testtrello-57ec7',
    storageBucket: 'testtrello-57ec7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuppkKiVrfLUnjuGAeDbIEH_XCBPV1mkM',
    appId: '1:724762452264:ios:20599b943227328905b01d',
    messagingSenderId: '724762452264',
    projectId: 'testtrello-57ec7',
    storageBucket: 'testtrello-57ec7.firebasestorage.app',
    iosBundleId: 'com.example.printReadyInvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuppkKiVrfLUnjuGAeDbIEH_XCBPV1mkM',
    appId: '1:724762452264:ios:20599b943227328905b01d',
    messagingSenderId: '724762452264',
    projectId: 'testtrello-57ec7',
    storageBucket: 'testtrello-57ec7.firebasestorage.app',
    iosBundleId: 'com.example.printReadyInvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADkAjs5WA8UFqB1vMTigUi7_1gFycdcPA',
    appId: '1:724762452264:web:da991670446d8fca05b01d',
    messagingSenderId: '724762452264',
    projectId: 'testtrello-57ec7',
    authDomain: 'testtrello-57ec7.firebaseapp.com',
    storageBucket: 'testtrello-57ec7.firebasestorage.app',
    measurementId: 'G-R8SW2C2EPV',
  );
}
